// ACTIONS type:
export const ADD_ANSWERS_THERAPY = 'ADD_ANSWERS_THERAPY';
export const ADD_ANSWERS_GENDER = 'ADD_ANSWERS_GENDER';
export const ADD_ANSWERS_OLD = 'ADD_ANSWERS_OLD';
export const ADD_ANSWERS_ISSUE = 'ADD_ANSWERS_ISSUE';
export const ADD_ANSWERS_LANGUAGE = 'ADD_ANSWERS_LANGUAGE';
export const FETCH_THERAPY = 'FETCH_THERAPY';